# ## ~/dotfiles/zsh/zshrc
#
# Simple control file that loads additional modules as needed.
#
# Author: Tristan Blease <tristan@bleaseinteractive.com>
# Website: tristanblease.com
# Updated: 6/15/12
#

# Load all enabled modules
for file in ~/dotfiles/zsh/modules/*; do
  source $file
done